name = "createing"
author = "raftario"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40e547bce9421e809cc0daebd6aa1a57f4a0c6e46378cf3565fa44aba55771e5"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
