name = "createing"
author = "raftario"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03854e895e51dc71ce3c69af4c0fff007a4c6aa3cdc33f7326fb66704d987634"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
