name = "createing"
author = "raftario"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c24057b89f8c9b39755f74a1afff6542cf1ef8c32370ae243dfb15c3f9f8dbfa"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
