name = "createing"
author = "raftario"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73e4ada0c6a56a5db5a31c1c3c7a7d404c6ca92238a925623011e91b45d207a2"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
