name = "createing"
author = "raftario"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18ad72c88e44fb0954693922a358b859d0398689b1c7124b240e00d5bdd3e613"

[versions]
fabric = "0.16.2"
minecraft = "1.20.1"
